services:
  auth-service:
    image: ghcr.io/advprog-2026-b18-project/json-auth-service:latest
    container_name: auth-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    restart: always