spring.application.name=json-auth-service

# Neon PostgreSQL
spring.datasource.url=${DB_URL_AUTH}
spring.datasource.username=${DB_USER_AUTH}
spring.datasource.password=${DB_PASS_AUTH}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
app.jwt.secret=${JWT_SECRET}
