ALTER TABLE users
    ADD COLUMN IF NOT EXISTS total_orders INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS completed_orders INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS avg_rating DOUBLE PRECISION DEFAULT 0.0;
